version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/sibaritta/sibaritta-frontend:anyer
    container_name: base-sibaritta-anyer
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - 3007:3000
    environment:
      VIRTUAL_HOST: anyer.web.v2.sibaritta.mensorestudio.com
      LETSENCRYPT_HOST: anyer.web.v2.sibaritta.mensorestudio.com
      LETSENCRYPT_EMAIL: arianvaldivieso@gmail.com

networks:
  proxy:
    external: true
