version: "3"
services:
  app:
    name: 
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/sibaritta/sibaritta-frontend
    container_name: base-sibaritta-frontend
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - 3005:3000
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: arianvaldivieso@gmail.com

networks:
  proxy:
    external: true
