version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/mensorestudio01/sibaritta-web
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - 3000:3000
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: wiljoseflores@gmail.com

networks:
  proxy:
    external: true
